/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_protocol_2eproto__INCLUDED
#define PROTOBUF_C_protocol_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _Protocol__MultiSaveCommand Protocol__MultiSaveCommand;
typedef struct _Protocol__MultiSaveCommand__SaveCommand Protocol__MultiSaveCommand__SaveCommand;
typedef struct _Protocol__MultiSaveCommand__SaveCommand__Metadata Protocol__MultiSaveCommand__SaveCommand__Metadata;
typedef struct _Protocol__MultiSaveCommand__SaveCommand__Content Protocol__MultiSaveCommand__SaveCommand__Content;
typedef struct _Protocol__MultiSaveCommand__SaveCommand__Edge Protocol__MultiSaveCommand__SaveCommand__Edge;
typedef struct _Protocol__MultiSaveCommand__SaveCommand__Vertex Protocol__MultiSaveCommand__SaveCommand__Vertex;
typedef struct _Protocol__LoadCommand Protocol__LoadCommand;
typedef struct _Protocol__LoadCommand__Edge Protocol__LoadCommand__Edge;
typedef struct _Protocol__LoadCommand__GraphView Protocol__LoadCommand__GraphView;
typedef struct _Protocol__LoadCommand__ContentView Protocol__LoadCommand__ContentView;
typedef struct _Protocol__LoadCommand__SearchView Protocol__LoadCommand__SearchView;
typedef struct _Protocol__LoadCommand__Vertex Protocol__LoadCommand__Vertex;
typedef struct _Protocol__MultiCommand Protocol__MultiCommand;
typedef struct _Protocol__Vertex Protocol__Vertex;
typedef struct _Protocol__GraphView Protocol__GraphView;
typedef struct _Protocol__ContentView Protocol__ContentView;
typedef struct _Protocol__SearchView Protocol__SearchView;


/* --- enums --- */

typedef enum _Protocol__MultiSaveCommand__SaveCommand__Metadata__SecCommand {
  PROTOCOL__MULTI_SAVE_COMMAND__SAVE_COMMAND__METADATA__SEC_COMMAND__csha3 = 0,
  PROTOCOL__MULTI_SAVE_COMMAND__SAVE_COMMAND__METADATA__SEC_COMMAND__cluceneUid = 1,
  PROTOCOL__MULTI_SAVE_COMMAND__SAVE_COMMAND__METADATA__SEC_COMMAND__ctime = 2,
  PROTOCOL__MULTI_SAVE_COMMAND__SAVE_COMMAND__METADATA__SEC_COMMAND__cauthor = 3,
  PROTOCOL__MULTI_SAVE_COMMAND__SAVE_COMMAND__METADATA__SEC_COMMAND__cprevSha3 = 4,
  PROTOCOL__MULTI_SAVE_COMMAND__SAVE_COMMAND__METADATA__SEC_COMMAND__clocation = 5,
  PROTOCOL__MULTI_SAVE_COMMAND__SAVE_COMMAND__METADATA__SEC_COMMAND__cseller = 6,
  PROTOCOL__MULTI_SAVE_COMMAND__SAVE_COMMAND__METADATA__SEC_COMMAND__cperiod = 7,
  PROTOCOL__MULTI_SAVE_COMMAND__SAVE_COMMAND__METADATA__SEC_COMMAND__csha3Contract = 8
} Protocol__MultiSaveCommand__SaveCommand__Metadata__SecCommand;
typedef enum _Protocol__MultiSaveCommand__SaveCommand__Content__SecCommand {
  PROTOCOL__MULTI_SAVE_COMMAND__SAVE_COMMAND__CONTENT__SEC_COMMAND__cdoc = 0,
  PROTOCOL__MULTI_SAVE_COMMAND__SAVE_COMMAND__CONTENT__SEC_COMMAND__csummary = 1
} Protocol__MultiSaveCommand__SaveCommand__Content__SecCommand;
typedef enum _Protocol__MultiSaveCommand__SaveCommand__Edge__SecCommand {
  PROTOCOL__MULTI_SAVE_COMMAND__SAVE_COMMAND__EDGE__SEC_COMMAND__cinEdge = 0,
  PROTOCOL__MULTI_SAVE_COMMAND__SAVE_COMMAND__EDGE__SEC_COMMAND__cedge = 1
} Protocol__MultiSaveCommand__SaveCommand__Edge__SecCommand;
typedef enum _Protocol__MultiSaveCommand__SaveCommand__Vertex__SecCommand {
  PROTOCOL__MULTI_SAVE_COMMAND__SAVE_COMMAND__VERTEX__SEC_COMMAND__ccreateVertex = 0,
  PROTOCOL__MULTI_SAVE_COMMAND__SAVE_COMMAND__VERTEX__SEC_COMMAND__csetSize = 1,
  PROTOCOL__MULTI_SAVE_COMMAND__SAVE_COMMAND__VERTEX__SEC_COMMAND__caddEdge = 2,
  PROTOCOL__MULTI_SAVE_COMMAND__SAVE_COMMAND__VERTEX__SEC_COMMAND__caddBack_edge = 3
} Protocol__MultiSaveCommand__SaveCommand__Vertex__SecCommand;
typedef enum _Protocol__MultiSaveCommand__SaveCommand__Type {
  PROTOCOL__MULTI_SAVE_COMMAND__SAVE_COMMAND__TYPE__cmetadata = 0,
  PROTOCOL__MULTI_SAVE_COMMAND__SAVE_COMMAND__TYPE__ccontent = 1,
  PROTOCOL__MULTI_SAVE_COMMAND__SAVE_COMMAND__TYPE__cedge = 2,
  PROTOCOL__MULTI_SAVE_COMMAND__SAVE_COMMAND__TYPE__cvertex = 3
} Protocol__MultiSaveCommand__SaveCommand__Type;
typedef enum _Protocol__LoadCommand__Edge__SecCommand {
  PROTOCOL__LOAD_COMMAND__EDGE__SEC_COMMAND__cinEdge = 0,
  PROTOCOL__LOAD_COMMAND__EDGE__SEC_COMMAND__cedge = 1
} Protocol__LoadCommand__Edge__SecCommand;
typedef enum _Protocol__LoadCommand__Type {
  PROTOCOL__LOAD_COMMAND__TYPE__cgraphView = 0,
  PROTOCOL__LOAD_COMMAND__TYPE__ccontentView = 1,
  PROTOCOL__LOAD_COMMAND__TYPE__csearchView = 2,
  PROTOCOL__LOAD_COMMAND__TYPE__cvertex = 3,
  PROTOCOL__LOAD_COMMAND__TYPE__crepair = 4
} Protocol__LoadCommand__Type;
typedef enum _Protocol__MultiCommand__Save {
  PROTOCOL__MULTI_COMMAND__SAVE__TRUE = 0,
  PROTOCOL__MULTI_COMMAND__SAVE__FALSE = 1
} Protocol__MultiCommand__Save;

/* --- messages --- */

struct  _Protocol__MultiSaveCommand__SaveCommand__Metadata
{
  ProtobufCMessage base;
  Protocol__MultiSaveCommand__SaveCommand__Metadata__SecCommand seccommand;
  ProtobufCBinaryData position;
  protobuf_c_boolean has_sha3;
  ProtobufCBinaryData sha3;
  protobuf_c_boolean has_luceneuid;
  int64_t luceneuid;
  protobuf_c_boolean has_time;
  int32_t time;
  protobuf_c_boolean has_author;
  ProtobufCBinaryData author;
  size_t n_prevsha3;
  ProtobufCBinaryData *prevsha3;
  protobuf_c_boolean has_location;
  ProtobufCBinaryData location;
  protobuf_c_boolean has_seller;
  ProtobufCBinaryData seller;
  protobuf_c_boolean has_period;
  ProtobufCBinaryData period;
  protobuf_c_boolean has_sha3contract;
  ProtobufCBinaryData sha3contract;
};
#define PROTOCOL__MULTI_SAVE_COMMAND__SAVE_COMMAND__METADATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protocol__multi_save_command__save_command__metadata__descriptor) \
    , 0, {0,NULL}, 0,{0,NULL}, 0,0, 0,0, 0,{0,NULL}, 0,NULL, 0,{0,NULL}, 0,{0,NULL}, 0,{0,NULL}, 0,{0,NULL} }


struct  _Protocol__MultiSaveCommand__SaveCommand__Content
{
  ProtobufCMessage base;
  Protocol__MultiSaveCommand__SaveCommand__Content__SecCommand seccommand;
  ProtobufCBinaryData position;
  ProtobufCBinaryData data;
};
#define PROTOCOL__MULTI_SAVE_COMMAND__SAVE_COMMAND__CONTENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protocol__multi_save_command__save_command__content__descriptor) \
    , 0, {0,NULL}, {0,NULL} }


struct  _Protocol__MultiSaveCommand__SaveCommand__Edge
{
  ProtobufCMessage base;
  Protocol__MultiSaveCommand__SaveCommand__Edge__SecCommand seccommand;
  protobuf_c_boolean has_position;
  ProtobufCBinaryData position;
  protobuf_c_boolean has_edge;
  ProtobufCBinaryData edge;
  ProtobufCBinaryData data;
};
#define PROTOCOL__MULTI_SAVE_COMMAND__SAVE_COMMAND__EDGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protocol__multi_save_command__save_command__edge__descriptor) \
    , 0, 0,{0,NULL}, 0,{0,NULL}, {0,NULL} }


struct  _Protocol__MultiSaveCommand__SaveCommand__Vertex
{
  ProtobufCMessage base;
  Protocol__MultiSaveCommand__SaveCommand__Vertex__SecCommand seccommand;
  protobuf_c_boolean has_size;
  ProtobufCBinaryData size;
  protobuf_c_boolean has_edge;
  ProtobufCBinaryData edge;
};
#define PROTOCOL__MULTI_SAVE_COMMAND__SAVE_COMMAND__VERTEX__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protocol__multi_save_command__save_command__vertex__descriptor) \
    , 0, 0,{0,NULL}, 0,{0,NULL} }


struct  _Protocol__MultiSaveCommand__SaveCommand
{
  ProtobufCMessage base;
  Protocol__MultiSaveCommand__SaveCommand__Type type;
  Protocol__MultiSaveCommand__SaveCommand__Metadata *metadata;
  Protocol__MultiSaveCommand__SaveCommand__Content *content;
  Protocol__MultiSaveCommand__SaveCommand__Edge *edge;
  Protocol__MultiSaveCommand__SaveCommand__Vertex *vertex;
};
#define PROTOCOL__MULTI_SAVE_COMMAND__SAVE_COMMAND__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protocol__multi_save_command__save_command__descriptor) \
    , 0, NULL, NULL, NULL, NULL }


struct  _Protocol__MultiSaveCommand
{
  ProtobufCMessage base;
  int64_t key;
  size_t n_savecommand;
  Protocol__MultiSaveCommand__SaveCommand **savecommand;
};
#define PROTOCOL__MULTI_SAVE_COMMAND__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protocol__multi_save_command__descriptor) \
    , 0, 0,NULL }


struct  _Protocol__LoadCommand__Edge
{
  ProtobufCMessage base;
  Protocol__LoadCommand__Edge__SecCommand seccommand;
  int64_t key;
  protobuf_c_boolean has_position;
  ProtobufCBinaryData position;
  protobuf_c_boolean has_edge;
  ProtobufCBinaryData edge;
};
#define PROTOCOL__LOAD_COMMAND__EDGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protocol__load_command__edge__descriptor) \
    , 0, 0, 0,{0,NULL}, 0,{0,NULL} }


struct  _Protocol__LoadCommand__GraphView
{
  ProtobufCMessage base;
  size_t n_key;
  int64_t *key;
  size_t n_position;
  ProtobufCBinaryData *position;
  size_t n_edges;
  Protocol__LoadCommand__Edge **edges;
};
#define PROTOCOL__LOAD_COMMAND__GRAPH_VIEW__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protocol__load_command__graph_view__descriptor) \
    , 0,NULL, 0,NULL, 0,NULL }


struct  _Protocol__LoadCommand__ContentView
{
  ProtobufCMessage base;
  int64_t key;
  ProtobufCBinaryData position;
  ProtobufCBinaryData start_position;
};
#define PROTOCOL__LOAD_COMMAND__CONTENT_VIEW__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protocol__load_command__content_view__descriptor) \
    , 0, {0,NULL}, {0,NULL} }


struct  _Protocol__LoadCommand__SearchView
{
  ProtobufCMessage base;
  size_t n_key;
  int64_t *key;
  size_t n_position;
  ProtobufCBinaryData *position;
};
#define PROTOCOL__LOAD_COMMAND__SEARCH_VIEW__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protocol__load_command__search_view__descriptor) \
    , 0,NULL, 0,NULL }


struct  _Protocol__LoadCommand__Vertex
{
  ProtobufCMessage base;
  int64_t key;
};
#define PROTOCOL__LOAD_COMMAND__VERTEX__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protocol__load_command__vertex__descriptor) \
    , 0 }


struct  _Protocol__LoadCommand
{
  ProtobufCMessage base;
  Protocol__LoadCommand__Type type;
  Protocol__LoadCommand__GraphView *graphview;
  Protocol__LoadCommand__ContentView *contentview;
  Protocol__LoadCommand__SearchView *searchview;
  Protocol__LoadCommand__Vertex *vertex;
};
#define PROTOCOL__LOAD_COMMAND__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protocol__load_command__descriptor) \
    , 0, NULL, NULL, NULL, NULL }


struct  _Protocol__MultiCommand
{
  ProtobufCMessage base;
  Protocol__MultiCommand__Save save;
  Protocol__LoadCommand *loadcommand;
  Protocol__MultiSaveCommand *multisavecommand;
};
#define PROTOCOL__MULTI_COMMAND__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protocol__multi_command__descriptor) \
    , 0, NULL, NULL }


struct  _Protocol__Vertex
{
  ProtobufCMessage base;
  ProtobufCBinaryData size;
  size_t n_edges;
  ProtobufCBinaryData *edges;
  size_t n_back_edges;
  ProtobufCBinaryData *back_edges;
};
#define PROTOCOL__VERTEX__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protocol__vertex__descriptor) \
    , {0,NULL}, 0,NULL, 0,NULL }


struct  _Protocol__GraphView
{
  ProtobufCMessage base;
  size_t n_summaries;
  ProtobufCBinaryData *summaries;
  size_t n_sha3;
  ProtobufCBinaryData *sha3;
  size_t n_edges;
  ProtobufCBinaryData *edges;
};
#define PROTOCOL__GRAPH_VIEW__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protocol__graph_view__descriptor) \
    , 0,NULL, 0,NULL, 0,NULL }


struct  _Protocol__ContentView
{
  ProtobufCMessage base;
  size_t n_data;
  ProtobufCBinaryData *data;
  size_t n_luceneuid;
  int64_t *luceneuid;
};
#define PROTOCOL__CONTENT_VIEW__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protocol__content_view__descriptor) \
    , 0,NULL, 0,NULL }


struct  _Protocol__SearchView
{
  ProtobufCMessage base;
  size_t n_summaries;
  ProtobufCBinaryData *summaries;
  size_t n_sha3;
  ProtobufCBinaryData *sha3;
};
#define PROTOCOL__SEARCH_VIEW__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&protocol__search_view__descriptor) \
    , 0,NULL, 0,NULL }


/* Protocol__MultiSaveCommand__SaveCommand__Metadata methods */
void   protocol__multi_save_command__save_command__metadata__init
                     (Protocol__MultiSaveCommand__SaveCommand__Metadata         *message);
/* Protocol__MultiSaveCommand__SaveCommand__Content methods */
void   protocol__multi_save_command__save_command__content__init
                     (Protocol__MultiSaveCommand__SaveCommand__Content         *message);
/* Protocol__MultiSaveCommand__SaveCommand__Edge methods */
void   protocol__multi_save_command__save_command__edge__init
                     (Protocol__MultiSaveCommand__SaveCommand__Edge         *message);
/* Protocol__MultiSaveCommand__SaveCommand__Vertex methods */
void   protocol__multi_save_command__save_command__vertex__init
                     (Protocol__MultiSaveCommand__SaveCommand__Vertex         *message);
/* Protocol__MultiSaveCommand__SaveCommand methods */
void   protocol__multi_save_command__save_command__init
                     (Protocol__MultiSaveCommand__SaveCommand         *message);
/* Protocol__MultiSaveCommand methods */
void   protocol__multi_save_command__init
                     (Protocol__MultiSaveCommand         *message);
size_t protocol__multi_save_command__get_packed_size
                     (const Protocol__MultiSaveCommand   *message);
size_t protocol__multi_save_command__pack
                     (const Protocol__MultiSaveCommand   *message,
                      uint8_t             *out);
size_t protocol__multi_save_command__pack_to_buffer
                     (const Protocol__MultiSaveCommand   *message,
                      ProtobufCBuffer     *buffer);
Protocol__MultiSaveCommand *
       protocol__multi_save_command__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   protocol__multi_save_command__free_unpacked
                     (Protocol__MultiSaveCommand *message,
                      ProtobufCAllocator *allocator);
/* Protocol__LoadCommand__Edge methods */
void   protocol__load_command__edge__init
                     (Protocol__LoadCommand__Edge         *message);
/* Protocol__LoadCommand__GraphView methods */
void   protocol__load_command__graph_view__init
                     (Protocol__LoadCommand__GraphView         *message);
/* Protocol__LoadCommand__ContentView methods */
void   protocol__load_command__content_view__init
                     (Protocol__LoadCommand__ContentView         *message);
/* Protocol__LoadCommand__SearchView methods */
void   protocol__load_command__search_view__init
                     (Protocol__LoadCommand__SearchView         *message);
/* Protocol__LoadCommand__Vertex methods */
void   protocol__load_command__vertex__init
                     (Protocol__LoadCommand__Vertex         *message);
/* Protocol__LoadCommand methods */
void   protocol__load_command__init
                     (Protocol__LoadCommand         *message);
size_t protocol__load_command__get_packed_size
                     (const Protocol__LoadCommand   *message);
size_t protocol__load_command__pack
                     (const Protocol__LoadCommand   *message,
                      uint8_t             *out);
size_t protocol__load_command__pack_to_buffer
                     (const Protocol__LoadCommand   *message,
                      ProtobufCBuffer     *buffer);
Protocol__LoadCommand *
       protocol__load_command__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   protocol__load_command__free_unpacked
                     (Protocol__LoadCommand *message,
                      ProtobufCAllocator *allocator);
/* Protocol__MultiCommand methods */
void   protocol__multi_command__init
                     (Protocol__MultiCommand         *message);
size_t protocol__multi_command__get_packed_size
                     (const Protocol__MultiCommand   *message);
size_t protocol__multi_command__pack
                     (const Protocol__MultiCommand   *message,
                      uint8_t             *out);
size_t protocol__multi_command__pack_to_buffer
                     (const Protocol__MultiCommand   *message,
                      ProtobufCBuffer     *buffer);
Protocol__MultiCommand *
       protocol__multi_command__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   protocol__multi_command__free_unpacked
                     (Protocol__MultiCommand *message,
                      ProtobufCAllocator *allocator);
/* Protocol__Vertex methods */
void   protocol__vertex__init
                     (Protocol__Vertex         *message);
size_t protocol__vertex__get_packed_size
                     (const Protocol__Vertex   *message);
size_t protocol__vertex__pack
                     (const Protocol__Vertex   *message,
                      uint8_t             *out);
size_t protocol__vertex__pack_to_buffer
                     (const Protocol__Vertex   *message,
                      ProtobufCBuffer     *buffer);
Protocol__Vertex *
       protocol__vertex__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   protocol__vertex__free_unpacked
                     (Protocol__Vertex *message,
                      ProtobufCAllocator *allocator);
/* Protocol__GraphView methods */
void   protocol__graph_view__init
                     (Protocol__GraphView         *message);
size_t protocol__graph_view__get_packed_size
                     (const Protocol__GraphView   *message);
size_t protocol__graph_view__pack
                     (const Protocol__GraphView   *message,
                      uint8_t             *out);
size_t protocol__graph_view__pack_to_buffer
                     (const Protocol__GraphView   *message,
                      ProtobufCBuffer     *buffer);
Protocol__GraphView *
       protocol__graph_view__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   protocol__graph_view__free_unpacked
                     (Protocol__GraphView *message,
                      ProtobufCAllocator *allocator);
/* Protocol__ContentView methods */
void   protocol__content_view__init
                     (Protocol__ContentView         *message);
size_t protocol__content_view__get_packed_size
                     (const Protocol__ContentView   *message);
size_t protocol__content_view__pack
                     (const Protocol__ContentView   *message,
                      uint8_t             *out);
size_t protocol__content_view__pack_to_buffer
                     (const Protocol__ContentView   *message,
                      ProtobufCBuffer     *buffer);
Protocol__ContentView *
       protocol__content_view__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   protocol__content_view__free_unpacked
                     (Protocol__ContentView *message,
                      ProtobufCAllocator *allocator);
/* Protocol__SearchView methods */
void   protocol__search_view__init
                     (Protocol__SearchView         *message);
size_t protocol__search_view__get_packed_size
                     (const Protocol__SearchView   *message);
size_t protocol__search_view__pack
                     (const Protocol__SearchView   *message,
                      uint8_t             *out);
size_t protocol__search_view__pack_to_buffer
                     (const Protocol__SearchView   *message,
                      ProtobufCBuffer     *buffer);
Protocol__SearchView *
       protocol__search_view__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   protocol__search_view__free_unpacked
                     (Protocol__SearchView *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Protocol__MultiSaveCommand__SaveCommand__Metadata_Closure)
                 (const Protocol__MultiSaveCommand__SaveCommand__Metadata *message,
                  void *closure_data);
typedef void (*Protocol__MultiSaveCommand__SaveCommand__Content_Closure)
                 (const Protocol__MultiSaveCommand__SaveCommand__Content *message,
                  void *closure_data);
typedef void (*Protocol__MultiSaveCommand__SaveCommand__Edge_Closure)
                 (const Protocol__MultiSaveCommand__SaveCommand__Edge *message,
                  void *closure_data);
typedef void (*Protocol__MultiSaveCommand__SaveCommand__Vertex_Closure)
                 (const Protocol__MultiSaveCommand__SaveCommand__Vertex *message,
                  void *closure_data);
typedef void (*Protocol__MultiSaveCommand__SaveCommand_Closure)
                 (const Protocol__MultiSaveCommand__SaveCommand *message,
                  void *closure_data);
typedef void (*Protocol__MultiSaveCommand_Closure)
                 (const Protocol__MultiSaveCommand *message,
                  void *closure_data);
typedef void (*Protocol__LoadCommand__Edge_Closure)
                 (const Protocol__LoadCommand__Edge *message,
                  void *closure_data);
typedef void (*Protocol__LoadCommand__GraphView_Closure)
                 (const Protocol__LoadCommand__GraphView *message,
                  void *closure_data);
typedef void (*Protocol__LoadCommand__ContentView_Closure)
                 (const Protocol__LoadCommand__ContentView *message,
                  void *closure_data);
typedef void (*Protocol__LoadCommand__SearchView_Closure)
                 (const Protocol__LoadCommand__SearchView *message,
                  void *closure_data);
typedef void (*Protocol__LoadCommand__Vertex_Closure)
                 (const Protocol__LoadCommand__Vertex *message,
                  void *closure_data);
typedef void (*Protocol__LoadCommand_Closure)
                 (const Protocol__LoadCommand *message,
                  void *closure_data);
typedef void (*Protocol__MultiCommand_Closure)
                 (const Protocol__MultiCommand *message,
                  void *closure_data);
typedef void (*Protocol__Vertex_Closure)
                 (const Protocol__Vertex *message,
                  void *closure_data);
typedef void (*Protocol__GraphView_Closure)
                 (const Protocol__GraphView *message,
                  void *closure_data);
typedef void (*Protocol__ContentView_Closure)
                 (const Protocol__ContentView *message,
                  void *closure_data);
typedef void (*Protocol__SearchView_Closure)
                 (const Protocol__SearchView *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor protocol__multi_save_command__descriptor;
extern const ProtobufCMessageDescriptor protocol__multi_save_command__save_command__descriptor;
extern const ProtobufCMessageDescriptor protocol__multi_save_command__save_command__metadata__descriptor;
extern const ProtobufCEnumDescriptor    protocol__multi_save_command__save_command__metadata__sec_command__descriptor;
extern const ProtobufCMessageDescriptor protocol__multi_save_command__save_command__content__descriptor;
extern const ProtobufCEnumDescriptor    protocol__multi_save_command__save_command__content__sec_command__descriptor;
extern const ProtobufCMessageDescriptor protocol__multi_save_command__save_command__edge__descriptor;
extern const ProtobufCEnumDescriptor    protocol__multi_save_command__save_command__edge__sec_command__descriptor;
extern const ProtobufCMessageDescriptor protocol__multi_save_command__save_command__vertex__descriptor;
extern const ProtobufCEnumDescriptor    protocol__multi_save_command__save_command__vertex__sec_command__descriptor;
extern const ProtobufCEnumDescriptor    protocol__multi_save_command__save_command__type__descriptor;
extern const ProtobufCMessageDescriptor protocol__load_command__descriptor;
extern const ProtobufCMessageDescriptor protocol__load_command__edge__descriptor;
extern const ProtobufCEnumDescriptor    protocol__load_command__edge__sec_command__descriptor;
extern const ProtobufCMessageDescriptor protocol__load_command__graph_view__descriptor;
extern const ProtobufCMessageDescriptor protocol__load_command__content_view__descriptor;
extern const ProtobufCMessageDescriptor protocol__load_command__search_view__descriptor;
extern const ProtobufCMessageDescriptor protocol__load_command__vertex__descriptor;
extern const ProtobufCEnumDescriptor    protocol__load_command__type__descriptor;
extern const ProtobufCMessageDescriptor protocol__multi_command__descriptor;
extern const ProtobufCEnumDescriptor    protocol__multi_command__save__descriptor;
extern const ProtobufCMessageDescriptor protocol__vertex__descriptor;
extern const ProtobufCMessageDescriptor protocol__graph_view__descriptor;
extern const ProtobufCMessageDescriptor protocol__content_view__descriptor;
extern const ProtobufCMessageDescriptor protocol__search_view__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_protocol_2eproto__INCLUDED */
