/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "protocol.pb-c.h"
void   protocol__multi_save_command__save_command__metadata__init
                     (Protocol__MultiSaveCommand__SaveCommand__Metadata         *message)
{
  static Protocol__MultiSaveCommand__SaveCommand__Metadata init_value = PROTOCOL__MULTI_SAVE_COMMAND__SAVE_COMMAND__METADATA__INIT;
  *message = init_value;
}
void   protocol__multi_save_command__save_command__content__init
                     (Protocol__MultiSaveCommand__SaveCommand__Content         *message)
{
  static Protocol__MultiSaveCommand__SaveCommand__Content init_value = PROTOCOL__MULTI_SAVE_COMMAND__SAVE_COMMAND__CONTENT__INIT;
  *message = init_value;
}
void   protocol__multi_save_command__save_command__edge__init
                     (Protocol__MultiSaveCommand__SaveCommand__Edge         *message)
{
  static Protocol__MultiSaveCommand__SaveCommand__Edge init_value = PROTOCOL__MULTI_SAVE_COMMAND__SAVE_COMMAND__EDGE__INIT;
  *message = init_value;
}
void   protocol__multi_save_command__save_command__vertex__init
                     (Protocol__MultiSaveCommand__SaveCommand__Vertex         *message)
{
  static Protocol__MultiSaveCommand__SaveCommand__Vertex init_value = PROTOCOL__MULTI_SAVE_COMMAND__SAVE_COMMAND__VERTEX__INIT;
  *message = init_value;
}
void   protocol__multi_save_command__save_command__init
                     (Protocol__MultiSaveCommand__SaveCommand         *message)
{
  static Protocol__MultiSaveCommand__SaveCommand init_value = PROTOCOL__MULTI_SAVE_COMMAND__SAVE_COMMAND__INIT;
  *message = init_value;
}
void   protocol__multi_save_command__init
                     (Protocol__MultiSaveCommand         *message)
{
  static Protocol__MultiSaveCommand init_value = PROTOCOL__MULTI_SAVE_COMMAND__INIT;
  *message = init_value;
}
size_t protocol__multi_save_command__get_packed_size
                     (const Protocol__MultiSaveCommand *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protocol__multi_save_command__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protocol__multi_save_command__pack
                     (const Protocol__MultiSaveCommand *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protocol__multi_save_command__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protocol__multi_save_command__pack_to_buffer
                     (const Protocol__MultiSaveCommand *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protocol__multi_save_command__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protocol__MultiSaveCommand *
       protocol__multi_save_command__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protocol__MultiSaveCommand *)
     protobuf_c_message_unpack (&protocol__multi_save_command__descriptor,
                                allocator, len, data);
}
void   protocol__multi_save_command__free_unpacked
                     (Protocol__MultiSaveCommand *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protocol__multi_save_command__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   protocol__load_command__edge__init
                     (Protocol__LoadCommand__Edge         *message)
{
  static Protocol__LoadCommand__Edge init_value = PROTOCOL__LOAD_COMMAND__EDGE__INIT;
  *message = init_value;
}
void   protocol__load_command__graph_view__init
                     (Protocol__LoadCommand__GraphView         *message)
{
  static Protocol__LoadCommand__GraphView init_value = PROTOCOL__LOAD_COMMAND__GRAPH_VIEW__INIT;
  *message = init_value;
}
void   protocol__load_command__content_view__init
                     (Protocol__LoadCommand__ContentView         *message)
{
  static Protocol__LoadCommand__ContentView init_value = PROTOCOL__LOAD_COMMAND__CONTENT_VIEW__INIT;
  *message = init_value;
}
void   protocol__load_command__search_view__init
                     (Protocol__LoadCommand__SearchView         *message)
{
  static Protocol__LoadCommand__SearchView init_value = PROTOCOL__LOAD_COMMAND__SEARCH_VIEW__INIT;
  *message = init_value;
}
void   protocol__load_command__vertex__init
                     (Protocol__LoadCommand__Vertex         *message)
{
  static Protocol__LoadCommand__Vertex init_value = PROTOCOL__LOAD_COMMAND__VERTEX__INIT;
  *message = init_value;
}
void   protocol__load_command__init
                     (Protocol__LoadCommand         *message)
{
  static Protocol__LoadCommand init_value = PROTOCOL__LOAD_COMMAND__INIT;
  *message = init_value;
}
size_t protocol__load_command__get_packed_size
                     (const Protocol__LoadCommand *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protocol__load_command__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protocol__load_command__pack
                     (const Protocol__LoadCommand *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protocol__load_command__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protocol__load_command__pack_to_buffer
                     (const Protocol__LoadCommand *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protocol__load_command__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protocol__LoadCommand *
       protocol__load_command__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protocol__LoadCommand *)
     protobuf_c_message_unpack (&protocol__load_command__descriptor,
                                allocator, len, data);
}
void   protocol__load_command__free_unpacked
                     (Protocol__LoadCommand *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protocol__load_command__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   protocol__multi_command__init
                     (Protocol__MultiCommand         *message)
{
  static Protocol__MultiCommand init_value = PROTOCOL__MULTI_COMMAND__INIT;
  *message = init_value;
}
size_t protocol__multi_command__get_packed_size
                     (const Protocol__MultiCommand *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protocol__multi_command__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protocol__multi_command__pack
                     (const Protocol__MultiCommand *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protocol__multi_command__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protocol__multi_command__pack_to_buffer
                     (const Protocol__MultiCommand *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protocol__multi_command__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protocol__MultiCommand *
       protocol__multi_command__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protocol__MultiCommand *)
     protobuf_c_message_unpack (&protocol__multi_command__descriptor,
                                allocator, len, data);
}
void   protocol__multi_command__free_unpacked
                     (Protocol__MultiCommand *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protocol__multi_command__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   protocol__vertex__init
                     (Protocol__Vertex         *message)
{
  static Protocol__Vertex init_value = PROTOCOL__VERTEX__INIT;
  *message = init_value;
}
size_t protocol__vertex__get_packed_size
                     (const Protocol__Vertex *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protocol__vertex__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protocol__vertex__pack
                     (const Protocol__Vertex *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protocol__vertex__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protocol__vertex__pack_to_buffer
                     (const Protocol__Vertex *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protocol__vertex__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protocol__Vertex *
       protocol__vertex__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protocol__Vertex *)
     protobuf_c_message_unpack (&protocol__vertex__descriptor,
                                allocator, len, data);
}
void   protocol__vertex__free_unpacked
                     (Protocol__Vertex *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protocol__vertex__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   protocol__graph_view__init
                     (Protocol__GraphView         *message)
{
  static Protocol__GraphView init_value = PROTOCOL__GRAPH_VIEW__INIT;
  *message = init_value;
}
size_t protocol__graph_view__get_packed_size
                     (const Protocol__GraphView *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protocol__graph_view__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protocol__graph_view__pack
                     (const Protocol__GraphView *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protocol__graph_view__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protocol__graph_view__pack_to_buffer
                     (const Protocol__GraphView *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protocol__graph_view__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protocol__GraphView *
       protocol__graph_view__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protocol__GraphView *)
     protobuf_c_message_unpack (&protocol__graph_view__descriptor,
                                allocator, len, data);
}
void   protocol__graph_view__free_unpacked
                     (Protocol__GraphView *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protocol__graph_view__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   protocol__content_view__init
                     (Protocol__ContentView         *message)
{
  static Protocol__ContentView init_value = PROTOCOL__CONTENT_VIEW__INIT;
  *message = init_value;
}
size_t protocol__content_view__get_packed_size
                     (const Protocol__ContentView *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protocol__content_view__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protocol__content_view__pack
                     (const Protocol__ContentView *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protocol__content_view__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protocol__content_view__pack_to_buffer
                     (const Protocol__ContentView *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protocol__content_view__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protocol__ContentView *
       protocol__content_view__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protocol__ContentView *)
     protobuf_c_message_unpack (&protocol__content_view__descriptor,
                                allocator, len, data);
}
void   protocol__content_view__free_unpacked
                     (Protocol__ContentView *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protocol__content_view__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   protocol__search_view__init
                     (Protocol__SearchView         *message)
{
  static Protocol__SearchView init_value = PROTOCOL__SEARCH_VIEW__INIT;
  *message = init_value;
}
size_t protocol__search_view__get_packed_size
                     (const Protocol__SearchView *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protocol__search_view__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t protocol__search_view__pack
                     (const Protocol__SearchView *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protocol__search_view__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t protocol__search_view__pack_to_buffer
                     (const Protocol__SearchView *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protocol__search_view__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Protocol__SearchView *
       protocol__search_view__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Protocol__SearchView *)
     protobuf_c_message_unpack (&protocol__search_view__descriptor,
                                allocator, len, data);
}
void   protocol__search_view__free_unpacked
                     (Protocol__SearchView *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &protocol__search_view__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
const ProtobufCEnumValue protocol__multi_save_command__save_command__metadata__sec_command__enum_values_by_number[9] =
{
  { "csha3", "PROTOCOL__MULTI_SAVE_COMMAND__SAVE_COMMAND__METADATA__SEC_COMMAND__CSHA3", 0 },
  { "cluceneUid", "PROTOCOL__MULTI_SAVE_COMMAND__SAVE_COMMAND__METADATA__SEC_COMMAND__CLUCENEUID", 1 },
  { "ctime", "PROTOCOL__MULTI_SAVE_COMMAND__SAVE_COMMAND__METADATA__SEC_COMMAND__CTIME", 2 },
  { "cauthor", "PROTOCOL__MULTI_SAVE_COMMAND__SAVE_COMMAND__METADATA__SEC_COMMAND__CAUTHOR", 3 },
  { "cprevSha3", "PROTOCOL__MULTI_SAVE_COMMAND__SAVE_COMMAND__METADATA__SEC_COMMAND__CPREVSHA3", 4 },
  { "clocation", "PROTOCOL__MULTI_SAVE_COMMAND__SAVE_COMMAND__METADATA__SEC_COMMAND__CLOCATION", 5 },
  { "cseller", "PROTOCOL__MULTI_SAVE_COMMAND__SAVE_COMMAND__METADATA__SEC_COMMAND__CSELLER", 6 },
  { "cperiod", "PROTOCOL__MULTI_SAVE_COMMAND__SAVE_COMMAND__METADATA__SEC_COMMAND__CPERIOD", 7 },
  { "csha3Contract", "PROTOCOL__MULTI_SAVE_COMMAND__SAVE_COMMAND__METADATA__SEC_COMMAND__CSHA3CONTRACT", 8 },
};
static const ProtobufCIntRange protocol__multi_save_command__save_command__metadata__sec_command__value_ranges[] = {
{0, 0},{0, 9}
};
const ProtobufCEnumValueIndex protocol__multi_save_command__save_command__metadata__sec_command__enum_values_by_name[9] =
{
  { "cauthor", 3 },
  { "clocation", 5 },
  { "cluceneUid", 1 },
  { "cperiod", 7 },
  { "cprevSha3", 4 },
  { "cseller", 6 },
  { "csha3", 0 },
  { "csha3Contract", 8 },
  { "ctime", 2 },
};
const ProtobufCEnumDescriptor protocol__multi_save_command__save_command__metadata__sec_command__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "protocol.MultiSaveCommand.SaveCommand.Metadata.SecCommand",
  "SecCommand",
  "Protocol__MultiSaveCommand__SaveCommand__Metadata__SecCommand",
  "protocol",
  9,
  protocol__multi_save_command__save_command__metadata__sec_command__enum_values_by_number,
  9,
  protocol__multi_save_command__save_command__metadata__sec_command__enum_values_by_name,
  1,
  protocol__multi_save_command__save_command__metadata__sec_command__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor protocol__multi_save_command__save_command__metadata__field_descriptors[11] =
{
  {
    "secCommand",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Protocol__MultiSaveCommand__SaveCommand__Metadata, seccommand),
    &protocol__multi_save_command__save_command__metadata__sec_command__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "position",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Protocol__MultiSaveCommand__SaveCommand__Metadata, position),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sha3",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Protocol__MultiSaveCommand__SaveCommand__Metadata, has_sha3),
    PROTOBUF_C_OFFSETOF(Protocol__MultiSaveCommand__SaveCommand__Metadata, sha3),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "luceneUid",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    PROTOBUF_C_OFFSETOF(Protocol__MultiSaveCommand__SaveCommand__Metadata, has_luceneuid),
    PROTOBUF_C_OFFSETOF(Protocol__MultiSaveCommand__SaveCommand__Metadata, luceneuid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "time",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(Protocol__MultiSaveCommand__SaveCommand__Metadata, has_time),
    PROTOBUF_C_OFFSETOF(Protocol__MultiSaveCommand__SaveCommand__Metadata, time),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "author",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Protocol__MultiSaveCommand__SaveCommand__Metadata, has_author),
    PROTOBUF_C_OFFSETOF(Protocol__MultiSaveCommand__SaveCommand__Metadata, author),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "prevSha3",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Protocol__MultiSaveCommand__SaveCommand__Metadata, n_prevsha3),
    PROTOBUF_C_OFFSETOF(Protocol__MultiSaveCommand__SaveCommand__Metadata, prevsha3),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "location",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Protocol__MultiSaveCommand__SaveCommand__Metadata, has_location),
    PROTOBUF_C_OFFSETOF(Protocol__MultiSaveCommand__SaveCommand__Metadata, location),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "seller",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Protocol__MultiSaveCommand__SaveCommand__Metadata, has_seller),
    PROTOBUF_C_OFFSETOF(Protocol__MultiSaveCommand__SaveCommand__Metadata, seller),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "period",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Protocol__MultiSaveCommand__SaveCommand__Metadata, has_period),
    PROTOBUF_C_OFFSETOF(Protocol__MultiSaveCommand__SaveCommand__Metadata, period),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sha3Contract",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Protocol__MultiSaveCommand__SaveCommand__Metadata, has_sha3contract),
    PROTOBUF_C_OFFSETOF(Protocol__MultiSaveCommand__SaveCommand__Metadata, sha3contract),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protocol__multi_save_command__save_command__metadata__field_indices_by_name[] = {
  5,   /* field[5] = author */
  7,   /* field[7] = location */
  3,   /* field[3] = luceneUid */
  9,   /* field[9] = period */
  1,   /* field[1] = position */
  6,   /* field[6] = prevSha3 */
  0,   /* field[0] = secCommand */
  8,   /* field[8] = seller */
  2,   /* field[2] = sha3 */
  10,   /* field[10] = sha3Contract */
  4,   /* field[4] = time */
};
static const ProtobufCIntRange protocol__multi_save_command__save_command__metadata__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor protocol__multi_save_command__save_command__metadata__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "protocol.MultiSaveCommand.SaveCommand.Metadata",
  "Metadata",
  "Protocol__MultiSaveCommand__SaveCommand__Metadata",
  "protocol",
  sizeof(Protocol__MultiSaveCommand__SaveCommand__Metadata),
  11,
  protocol__multi_save_command__save_command__metadata__field_descriptors,
  protocol__multi_save_command__save_command__metadata__field_indices_by_name,
  1,  protocol__multi_save_command__save_command__metadata__number_ranges,
  (ProtobufCMessageInit) protocol__multi_save_command__save_command__metadata__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue protocol__multi_save_command__save_command__content__sec_command__enum_values_by_number[2] =
{
  { "cdoc", "PROTOCOL__MULTI_SAVE_COMMAND__SAVE_COMMAND__CONTENT__SEC_COMMAND__CDOC", 0 },
  { "csummary", "PROTOCOL__MULTI_SAVE_COMMAND__SAVE_COMMAND__CONTENT__SEC_COMMAND__CSUMMARY", 1 },
};
static const ProtobufCIntRange protocol__multi_save_command__save_command__content__sec_command__value_ranges[] = {
{0, 0},{0, 2}
};
const ProtobufCEnumValueIndex protocol__multi_save_command__save_command__content__sec_command__enum_values_by_name[2] =
{
  { "cdoc", 0 },
  { "csummary", 1 },
};
const ProtobufCEnumDescriptor protocol__multi_save_command__save_command__content__sec_command__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "protocol.MultiSaveCommand.SaveCommand.Content.SecCommand",
  "SecCommand",
  "Protocol__MultiSaveCommand__SaveCommand__Content__SecCommand",
  "protocol",
  2,
  protocol__multi_save_command__save_command__content__sec_command__enum_values_by_number,
  2,
  protocol__multi_save_command__save_command__content__sec_command__enum_values_by_name,
  1,
  protocol__multi_save_command__save_command__content__sec_command__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor protocol__multi_save_command__save_command__content__field_descriptors[3] =
{
  {
    "secCommand",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Protocol__MultiSaveCommand__SaveCommand__Content, seccommand),
    &protocol__multi_save_command__save_command__content__sec_command__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "position",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Protocol__MultiSaveCommand__SaveCommand__Content, position),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Protocol__MultiSaveCommand__SaveCommand__Content, data),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protocol__multi_save_command__save_command__content__field_indices_by_name[] = {
  2,   /* field[2] = data */
  1,   /* field[1] = position */
  0,   /* field[0] = secCommand */
};
static const ProtobufCIntRange protocol__multi_save_command__save_command__content__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor protocol__multi_save_command__save_command__content__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "protocol.MultiSaveCommand.SaveCommand.Content",
  "Content",
  "Protocol__MultiSaveCommand__SaveCommand__Content",
  "protocol",
  sizeof(Protocol__MultiSaveCommand__SaveCommand__Content),
  3,
  protocol__multi_save_command__save_command__content__field_descriptors,
  protocol__multi_save_command__save_command__content__field_indices_by_name,
  1,  protocol__multi_save_command__save_command__content__number_ranges,
  (ProtobufCMessageInit) protocol__multi_save_command__save_command__content__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue protocol__multi_save_command__save_command__edge__sec_command__enum_values_by_number[2] =
{
  { "cinEdge", "PROTOCOL__MULTI_SAVE_COMMAND__SAVE_COMMAND__EDGE__SEC_COMMAND__CINEDGE", 0 },
  { "cedge", "PROTOCOL__MULTI_SAVE_COMMAND__SAVE_COMMAND__EDGE__SEC_COMMAND__CEDGE", 1 },
};
static const ProtobufCIntRange protocol__multi_save_command__save_command__edge__sec_command__value_ranges[] = {
{0, 0},{0, 2}
};
const ProtobufCEnumValueIndex protocol__multi_save_command__save_command__edge__sec_command__enum_values_by_name[2] =
{
  { "cedge", 1 },
  { "cinEdge", 0 },
};
const ProtobufCEnumDescriptor protocol__multi_save_command__save_command__edge__sec_command__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "protocol.MultiSaveCommand.SaveCommand.Edge.SecCommand",
  "SecCommand",
  "Protocol__MultiSaveCommand__SaveCommand__Edge__SecCommand",
  "protocol",
  2,
  protocol__multi_save_command__save_command__edge__sec_command__enum_values_by_number,
  2,
  protocol__multi_save_command__save_command__edge__sec_command__enum_values_by_name,
  1,
  protocol__multi_save_command__save_command__edge__sec_command__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor protocol__multi_save_command__save_command__edge__field_descriptors[4] =
{
  {
    "secCommand",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Protocol__MultiSaveCommand__SaveCommand__Edge, seccommand),
    &protocol__multi_save_command__save_command__edge__sec_command__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "position",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Protocol__MultiSaveCommand__SaveCommand__Edge, has_position),
    PROTOBUF_C_OFFSETOF(Protocol__MultiSaveCommand__SaveCommand__Edge, position),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "edge",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Protocol__MultiSaveCommand__SaveCommand__Edge, has_edge),
    PROTOBUF_C_OFFSETOF(Protocol__MultiSaveCommand__SaveCommand__Edge, edge),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Protocol__MultiSaveCommand__SaveCommand__Edge, data),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protocol__multi_save_command__save_command__edge__field_indices_by_name[] = {
  3,   /* field[3] = data */
  2,   /* field[2] = edge */
  1,   /* field[1] = position */
  0,   /* field[0] = secCommand */
};
static const ProtobufCIntRange protocol__multi_save_command__save_command__edge__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor protocol__multi_save_command__save_command__edge__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "protocol.MultiSaveCommand.SaveCommand.Edge",
  "Edge",
  "Protocol__MultiSaveCommand__SaveCommand__Edge",
  "protocol",
  sizeof(Protocol__MultiSaveCommand__SaveCommand__Edge),
  4,
  protocol__multi_save_command__save_command__edge__field_descriptors,
  protocol__multi_save_command__save_command__edge__field_indices_by_name,
  1,  protocol__multi_save_command__save_command__edge__number_ranges,
  (ProtobufCMessageInit) protocol__multi_save_command__save_command__edge__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue protocol__multi_save_command__save_command__vertex__sec_command__enum_values_by_number[4] =
{
  { "ccreateVertex", "PROTOCOL__MULTI_SAVE_COMMAND__SAVE_COMMAND__VERTEX__SEC_COMMAND__CCREATEVERTEX", 0 },
  { "csetSize", "PROTOCOL__MULTI_SAVE_COMMAND__SAVE_COMMAND__VERTEX__SEC_COMMAND__CSETSIZE", 1 },
  { "caddEdge", "PROTOCOL__MULTI_SAVE_COMMAND__SAVE_COMMAND__VERTEX__SEC_COMMAND__CADDEDGE", 2 },
  { "caddBack_edge", "PROTOCOL__MULTI_SAVE_COMMAND__SAVE_COMMAND__VERTEX__SEC_COMMAND__CADDBACK_EDGE", 3 },
};
static const ProtobufCIntRange protocol__multi_save_command__save_command__vertex__sec_command__value_ranges[] = {
{0, 0},{0, 4}
};
const ProtobufCEnumValueIndex protocol__multi_save_command__save_command__vertex__sec_command__enum_values_by_name[4] =
{
  { "caddBack_edge", 3 },
  { "caddEdge", 2 },
  { "ccreateVertex", 0 },
  { "csetSize", 1 },
};
const ProtobufCEnumDescriptor protocol__multi_save_command__save_command__vertex__sec_command__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "protocol.MultiSaveCommand.SaveCommand.Vertex.SecCommand",
  "SecCommand",
  "Protocol__MultiSaveCommand__SaveCommand__Vertex__SecCommand",
  "protocol",
  4,
  protocol__multi_save_command__save_command__vertex__sec_command__enum_values_by_number,
  4,
  protocol__multi_save_command__save_command__vertex__sec_command__enum_values_by_name,
  1,
  protocol__multi_save_command__save_command__vertex__sec_command__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor protocol__multi_save_command__save_command__vertex__field_descriptors[3] =
{
  {
    "secCommand",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Protocol__MultiSaveCommand__SaveCommand__Vertex, seccommand),
    &protocol__multi_save_command__save_command__vertex__sec_command__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "size",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Protocol__MultiSaveCommand__SaveCommand__Vertex, has_size),
    PROTOBUF_C_OFFSETOF(Protocol__MultiSaveCommand__SaveCommand__Vertex, size),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "edge",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Protocol__MultiSaveCommand__SaveCommand__Vertex, has_edge),
    PROTOBUF_C_OFFSETOF(Protocol__MultiSaveCommand__SaveCommand__Vertex, edge),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protocol__multi_save_command__save_command__vertex__field_indices_by_name[] = {
  2,   /* field[2] = edge */
  0,   /* field[0] = secCommand */
  1,   /* field[1] = size */
};
static const ProtobufCIntRange protocol__multi_save_command__save_command__vertex__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor protocol__multi_save_command__save_command__vertex__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "protocol.MultiSaveCommand.SaveCommand.Vertex",
  "Vertex",
  "Protocol__MultiSaveCommand__SaveCommand__Vertex",
  "protocol",
  sizeof(Protocol__MultiSaveCommand__SaveCommand__Vertex),
  3,
  protocol__multi_save_command__save_command__vertex__field_descriptors,
  protocol__multi_save_command__save_command__vertex__field_indices_by_name,
  1,  protocol__multi_save_command__save_command__vertex__number_ranges,
  (ProtobufCMessageInit) protocol__multi_save_command__save_command__vertex__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue protocol__multi_save_command__save_command__type__enum_values_by_number[4] =
{
  { "cmetadata", "PROTOCOL__MULTI_SAVE_COMMAND__SAVE_COMMAND__TYPE__CMETADATA", 0 },
  { "ccontent", "PROTOCOL__MULTI_SAVE_COMMAND__SAVE_COMMAND__TYPE__CCONTENT", 1 },
  { "cedge", "PROTOCOL__MULTI_SAVE_COMMAND__SAVE_COMMAND__TYPE__CEDGE", 2 },
  { "cvertex", "PROTOCOL__MULTI_SAVE_COMMAND__SAVE_COMMAND__TYPE__CVERTEX", 3 },
};
static const ProtobufCIntRange protocol__multi_save_command__save_command__type__value_ranges[] = {
{0, 0},{0, 4}
};
const ProtobufCEnumValueIndex protocol__multi_save_command__save_command__type__enum_values_by_name[4] =
{
  { "ccontent", 1 },
  { "cedge", 2 },
  { "cmetadata", 0 },
  { "cvertex", 3 },
};
const ProtobufCEnumDescriptor protocol__multi_save_command__save_command__type__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "protocol.MultiSaveCommand.SaveCommand.Type",
  "Type",
  "Protocol__MultiSaveCommand__SaveCommand__Type",
  "protocol",
  4,
  protocol__multi_save_command__save_command__type__enum_values_by_number,
  4,
  protocol__multi_save_command__save_command__type__enum_values_by_name,
  1,
  protocol__multi_save_command__save_command__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor protocol__multi_save_command__save_command__field_descriptors[5] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Protocol__MultiSaveCommand__SaveCommand, type),
    &protocol__multi_save_command__save_command__type__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "metadata",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Protocol__MultiSaveCommand__SaveCommand, metadata),
    &protocol__multi_save_command__save_command__metadata__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "content",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Protocol__MultiSaveCommand__SaveCommand, content),
    &protocol__multi_save_command__save_command__content__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "edge",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Protocol__MultiSaveCommand__SaveCommand, edge),
    &protocol__multi_save_command__save_command__edge__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vertex",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Protocol__MultiSaveCommand__SaveCommand, vertex),
    &protocol__multi_save_command__save_command__vertex__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protocol__multi_save_command__save_command__field_indices_by_name[] = {
  2,   /* field[2] = content */
  3,   /* field[3] = edge */
  1,   /* field[1] = metadata */
  0,   /* field[0] = type */
  4,   /* field[4] = vertex */
};
static const ProtobufCIntRange protocol__multi_save_command__save_command__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor protocol__multi_save_command__save_command__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "protocol.MultiSaveCommand.SaveCommand",
  "SaveCommand",
  "Protocol__MultiSaveCommand__SaveCommand",
  "protocol",
  sizeof(Protocol__MultiSaveCommand__SaveCommand),
  5,
  protocol__multi_save_command__save_command__field_descriptors,
  protocol__multi_save_command__save_command__field_indices_by_name,
  1,  protocol__multi_save_command__save_command__number_ranges,
  (ProtobufCMessageInit) protocol__multi_save_command__save_command__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor protocol__multi_save_command__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Protocol__MultiSaveCommand, key),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "saveCommand",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Protocol__MultiSaveCommand, n_savecommand),
    PROTOBUF_C_OFFSETOF(Protocol__MultiSaveCommand, savecommand),
    &protocol__multi_save_command__save_command__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protocol__multi_save_command__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = saveCommand */
};
static const ProtobufCIntRange protocol__multi_save_command__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor protocol__multi_save_command__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "protocol.MultiSaveCommand",
  "MultiSaveCommand",
  "Protocol__MultiSaveCommand",
  "protocol",
  sizeof(Protocol__MultiSaveCommand),
  2,
  protocol__multi_save_command__field_descriptors,
  protocol__multi_save_command__field_indices_by_name,
  1,  protocol__multi_save_command__number_ranges,
  (ProtobufCMessageInit) protocol__multi_save_command__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue protocol__load_command__edge__sec_command__enum_values_by_number[2] =
{
  { "cinEdge", "PROTOCOL__LOAD_COMMAND__EDGE__SEC_COMMAND__CINEDGE", 0 },
  { "cedge", "PROTOCOL__LOAD_COMMAND__EDGE__SEC_COMMAND__CEDGE", 1 },
};
static const ProtobufCIntRange protocol__load_command__edge__sec_command__value_ranges[] = {
{0, 0},{0, 2}
};
const ProtobufCEnumValueIndex protocol__load_command__edge__sec_command__enum_values_by_name[2] =
{
  { "cedge", 1 },
  { "cinEdge", 0 },
};
const ProtobufCEnumDescriptor protocol__load_command__edge__sec_command__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "protocol.LoadCommand.Edge.SecCommand",
  "SecCommand",
  "Protocol__LoadCommand__Edge__SecCommand",
  "protocol",
  2,
  protocol__load_command__edge__sec_command__enum_values_by_number,
  2,
  protocol__load_command__edge__sec_command__enum_values_by_name,
  1,
  protocol__load_command__edge__sec_command__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor protocol__load_command__edge__field_descriptors[4] =
{
  {
    "secCommand",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Protocol__LoadCommand__Edge, seccommand),
    &protocol__load_command__edge__sec_command__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "key",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Protocol__LoadCommand__Edge, key),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "position",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Protocol__LoadCommand__Edge, has_position),
    PROTOBUF_C_OFFSETOF(Protocol__LoadCommand__Edge, position),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "edge",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Protocol__LoadCommand__Edge, has_edge),
    PROTOBUF_C_OFFSETOF(Protocol__LoadCommand__Edge, edge),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protocol__load_command__edge__field_indices_by_name[] = {
  3,   /* field[3] = edge */
  1,   /* field[1] = key */
  2,   /* field[2] = position */
  0,   /* field[0] = secCommand */
};
static const ProtobufCIntRange protocol__load_command__edge__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor protocol__load_command__edge__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "protocol.LoadCommand.Edge",
  "Edge",
  "Protocol__LoadCommand__Edge",
  "protocol",
  sizeof(Protocol__LoadCommand__Edge),
  4,
  protocol__load_command__edge__field_descriptors,
  protocol__load_command__edge__field_indices_by_name,
  1,  protocol__load_command__edge__number_ranges,
  (ProtobufCMessageInit) protocol__load_command__edge__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor protocol__load_command__graph_view__field_descriptors[3] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT64,
    PROTOBUF_C_OFFSETOF(Protocol__LoadCommand__GraphView, n_key),
    PROTOBUF_C_OFFSETOF(Protocol__LoadCommand__GraphView, key),
    NULL,
    NULL,
    1,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "position",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Protocol__LoadCommand__GraphView, n_position),
    PROTOBUF_C_OFFSETOF(Protocol__LoadCommand__GraphView, position),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "edges",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Protocol__LoadCommand__GraphView, n_edges),
    PROTOBUF_C_OFFSETOF(Protocol__LoadCommand__GraphView, edges),
    &protocol__load_command__edge__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protocol__load_command__graph_view__field_indices_by_name[] = {
  2,   /* field[2] = edges */
  0,   /* field[0] = key */
  1,   /* field[1] = position */
};
static const ProtobufCIntRange protocol__load_command__graph_view__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor protocol__load_command__graph_view__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "protocol.LoadCommand.GraphView",
  "GraphView",
  "Protocol__LoadCommand__GraphView",
  "protocol",
  sizeof(Protocol__LoadCommand__GraphView),
  3,
  protocol__load_command__graph_view__field_descriptors,
  protocol__load_command__graph_view__field_indices_by_name,
  1,  protocol__load_command__graph_view__number_ranges,
  (ProtobufCMessageInit) protocol__load_command__graph_view__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor protocol__load_command__content_view__field_descriptors[3] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Protocol__LoadCommand__ContentView, key),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "position",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Protocol__LoadCommand__ContentView, position),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "start_position",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Protocol__LoadCommand__ContentView, start_position),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protocol__load_command__content_view__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = position */
  2,   /* field[2] = start_position */
};
static const ProtobufCIntRange protocol__load_command__content_view__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor protocol__load_command__content_view__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "protocol.LoadCommand.ContentView",
  "ContentView",
  "Protocol__LoadCommand__ContentView",
  "protocol",
  sizeof(Protocol__LoadCommand__ContentView),
  3,
  protocol__load_command__content_view__field_descriptors,
  protocol__load_command__content_view__field_indices_by_name,
  1,  protocol__load_command__content_view__number_ranges,
  (ProtobufCMessageInit) protocol__load_command__content_view__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor protocol__load_command__search_view__field_descriptors[2] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT64,
    PROTOBUF_C_OFFSETOF(Protocol__LoadCommand__SearchView, n_key),
    PROTOBUF_C_OFFSETOF(Protocol__LoadCommand__SearchView, key),
    NULL,
    NULL,
    1,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "position",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Protocol__LoadCommand__SearchView, n_position),
    PROTOBUF_C_OFFSETOF(Protocol__LoadCommand__SearchView, position),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protocol__load_command__search_view__field_indices_by_name[] = {
  0,   /* field[0] = key */
  1,   /* field[1] = position */
};
static const ProtobufCIntRange protocol__load_command__search_view__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor protocol__load_command__search_view__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "protocol.LoadCommand.SearchView",
  "SearchView",
  "Protocol__LoadCommand__SearchView",
  "protocol",
  sizeof(Protocol__LoadCommand__SearchView),
  2,
  protocol__load_command__search_view__field_descriptors,
  protocol__load_command__search_view__field_indices_by_name,
  1,  protocol__load_command__search_view__number_ranges,
  (ProtobufCMessageInit) protocol__load_command__search_view__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor protocol__load_command__vertex__field_descriptors[1] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Protocol__LoadCommand__Vertex, key),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protocol__load_command__vertex__field_indices_by_name[] = {
  0,   /* field[0] = key */
};
static const ProtobufCIntRange protocol__load_command__vertex__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor protocol__load_command__vertex__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "protocol.LoadCommand.Vertex",
  "Vertex",
  "Protocol__LoadCommand__Vertex",
  "protocol",
  sizeof(Protocol__LoadCommand__Vertex),
  1,
  protocol__load_command__vertex__field_descriptors,
  protocol__load_command__vertex__field_indices_by_name,
  1,  protocol__load_command__vertex__number_ranges,
  (ProtobufCMessageInit) protocol__load_command__vertex__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue protocol__load_command__type__enum_values_by_number[5] =
{
  { "cgraphView", "PROTOCOL__LOAD_COMMAND__TYPE__CGRAPHVIEW", 0 },
  { "ccontentView", "PROTOCOL__LOAD_COMMAND__TYPE__CCONTENTVIEW", 1 },
  { "csearchView", "PROTOCOL__LOAD_COMMAND__TYPE__CSEARCHVIEW", 2 },
  { "cvertex", "PROTOCOL__LOAD_COMMAND__TYPE__CVERTEX", 3 },
  { "crepair", "PROTOCOL__LOAD_COMMAND__TYPE__CREPAIR", 4 },
};
static const ProtobufCIntRange protocol__load_command__type__value_ranges[] = {
{0, 0},{0, 5}
};
const ProtobufCEnumValueIndex protocol__load_command__type__enum_values_by_name[5] =
{
  { "ccontentView", 1 },
  { "cgraphView", 0 },
  { "crepair", 4 },
  { "csearchView", 2 },
  { "cvertex", 3 },
};
const ProtobufCEnumDescriptor protocol__load_command__type__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "protocol.LoadCommand.Type",
  "Type",
  "Protocol__LoadCommand__Type",
  "protocol",
  5,
  protocol__load_command__type__enum_values_by_number,
  5,
  protocol__load_command__type__enum_values_by_name,
  1,
  protocol__load_command__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor protocol__load_command__field_descriptors[5] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Protocol__LoadCommand, type),
    &protocol__load_command__type__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "graphView",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Protocol__LoadCommand, graphview),
    &protocol__load_command__graph_view__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "contentView",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Protocol__LoadCommand, contentview),
    &protocol__load_command__content_view__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "searchView",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Protocol__LoadCommand, searchview),
    &protocol__load_command__search_view__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vertex",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Protocol__LoadCommand, vertex),
    &protocol__load_command__vertex__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protocol__load_command__field_indices_by_name[] = {
  2,   /* field[2] = contentView */
  1,   /* field[1] = graphView */
  3,   /* field[3] = searchView */
  0,   /* field[0] = type */
  4,   /* field[4] = vertex */
};
static const ProtobufCIntRange protocol__load_command__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor protocol__load_command__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "protocol.LoadCommand",
  "LoadCommand",
  "Protocol__LoadCommand",
  "protocol",
  sizeof(Protocol__LoadCommand),
  5,
  protocol__load_command__field_descriptors,
  protocol__load_command__field_indices_by_name,
  1,  protocol__load_command__number_ranges,
  (ProtobufCMessageInit) protocol__load_command__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue protocol__multi_command__save__enum_values_by_number[2] =
{
  { "TRUE", "PROTOCOL__MULTI_COMMAND__SAVE__TRUE", 0 },
  { "FALSE", "PROTOCOL__MULTI_COMMAND__SAVE__FALSE", 1 },
};
static const ProtobufCIntRange protocol__multi_command__save__value_ranges[] = {
{0, 0},{0, 2}
};
const ProtobufCEnumValueIndex protocol__multi_command__save__enum_values_by_name[2] =
{
  { "FALSE", 1 },
  { "TRUE", 0 },
};
const ProtobufCEnumDescriptor protocol__multi_command__save__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "protocol.MultiCommand.Save",
  "Save",
  "Protocol__MultiCommand__Save",
  "protocol",
  2,
  protocol__multi_command__save__enum_values_by_number,
  2,
  protocol__multi_command__save__enum_values_by_name,
  1,
  protocol__multi_command__save__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor protocol__multi_command__field_descriptors[3] =
{
  {
    "save",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Protocol__MultiCommand, save),
    &protocol__multi_command__save__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "LoadCommand",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Protocol__MultiCommand, loadcommand),
    &protocol__load_command__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "multiSaveCommand",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Protocol__MultiCommand, multisavecommand),
    &protocol__multi_save_command__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protocol__multi_command__field_indices_by_name[] = {
  1,   /* field[1] = LoadCommand */
  2,   /* field[2] = multiSaveCommand */
  0,   /* field[0] = save */
};
static const ProtobufCIntRange protocol__multi_command__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor protocol__multi_command__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "protocol.MultiCommand",
  "MultiCommand",
  "Protocol__MultiCommand",
  "protocol",
  sizeof(Protocol__MultiCommand),
  3,
  protocol__multi_command__field_descriptors,
  protocol__multi_command__field_indices_by_name,
  1,  protocol__multi_command__number_ranges,
  (ProtobufCMessageInit) protocol__multi_command__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor protocol__vertex__field_descriptors[3] =
{
  {
    "size",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Protocol__Vertex, size),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "edges",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Protocol__Vertex, n_edges),
    PROTOBUF_C_OFFSETOF(Protocol__Vertex, edges),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "back_edges",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Protocol__Vertex, n_back_edges),
    PROTOBUF_C_OFFSETOF(Protocol__Vertex, back_edges),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protocol__vertex__field_indices_by_name[] = {
  2,   /* field[2] = back_edges */
  1,   /* field[1] = edges */
  0,   /* field[0] = size */
};
static const ProtobufCIntRange protocol__vertex__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor protocol__vertex__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "protocol.Vertex",
  "Vertex",
  "Protocol__Vertex",
  "protocol",
  sizeof(Protocol__Vertex),
  3,
  protocol__vertex__field_descriptors,
  protocol__vertex__field_indices_by_name,
  1,  protocol__vertex__number_ranges,
  (ProtobufCMessageInit) protocol__vertex__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor protocol__graph_view__field_descriptors[3] =
{
  {
    "summaries",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Protocol__GraphView, n_summaries),
    PROTOBUF_C_OFFSETOF(Protocol__GraphView, summaries),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sha3",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Protocol__GraphView, n_sha3),
    PROTOBUF_C_OFFSETOF(Protocol__GraphView, sha3),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "edges",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Protocol__GraphView, n_edges),
    PROTOBUF_C_OFFSETOF(Protocol__GraphView, edges),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protocol__graph_view__field_indices_by_name[] = {
  2,   /* field[2] = edges */
  1,   /* field[1] = sha3 */
  0,   /* field[0] = summaries */
};
static const ProtobufCIntRange protocol__graph_view__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor protocol__graph_view__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "protocol.GraphView",
  "GraphView",
  "Protocol__GraphView",
  "protocol",
  sizeof(Protocol__GraphView),
  3,
  protocol__graph_view__field_descriptors,
  protocol__graph_view__field_indices_by_name,
  1,  protocol__graph_view__number_ranges,
  (ProtobufCMessageInit) protocol__graph_view__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor protocol__content_view__field_descriptors[2] =
{
  {
    "data",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Protocol__ContentView, n_data),
    PROTOBUF_C_OFFSETOF(Protocol__ContentView, data),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "luceneUid",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_INT64,
    PROTOBUF_C_OFFSETOF(Protocol__ContentView, n_luceneuid),
    PROTOBUF_C_OFFSETOF(Protocol__ContentView, luceneuid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protocol__content_view__field_indices_by_name[] = {
  0,   /* field[0] = data */
  1,   /* field[1] = luceneUid */
};
static const ProtobufCIntRange protocol__content_view__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor protocol__content_view__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "protocol.ContentView",
  "ContentView",
  "Protocol__ContentView",
  "protocol",
  sizeof(Protocol__ContentView),
  2,
  protocol__content_view__field_descriptors,
  protocol__content_view__field_indices_by_name,
  1,  protocol__content_view__number_ranges,
  (ProtobufCMessageInit) protocol__content_view__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor protocol__search_view__field_descriptors[2] =
{
  {
    "summaries",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Protocol__SearchView, n_summaries),
    PROTOBUF_C_OFFSETOF(Protocol__SearchView, summaries),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sha3",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Protocol__SearchView, n_sha3),
    PROTOBUF_C_OFFSETOF(Protocol__SearchView, sha3),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned protocol__search_view__field_indices_by_name[] = {
  1,   /* field[1] = sha3 */
  0,   /* field[0] = summaries */
};
static const ProtobufCIntRange protocol__search_view__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor protocol__search_view__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "protocol.SearchView",
  "SearchView",
  "Protocol__SearchView",
  "protocol",
  sizeof(Protocol__SearchView),
  2,
  protocol__search_view__field_descriptors,
  protocol__search_view__field_indices_by_name,
  1,  protocol__search_view__number_ranges,
  (ProtobufCMessageInit) protocol__search_view__init,
  NULL,NULL,NULL    /* reserved[123] */
};
